#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [[ ! -f "/config/adguardhome-sync.yaml" ]]; then
    cp -a /defaults/adguardhome-sync.yaml /config/adguardhome-sync.yaml
fi

if [[ -z ${LSIO_NON_ROOT_USER} ]]; then
    lsiown -R abc:abc \
        /config
fi
