#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [[ ! -f "/config/adguardhome-sync.yaml" ]]; then
    cp -a /defaults/adguardhome-sync.yaml /config/adguardhome-sync.yaml
fi

lsiown -R abc:abc \
    /config
