#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [[ -n ${LSIO_NON_ROOT_USER} ]]; then
    exec \
        s6-notifyoncheck -d -n 300 -w 1000 \
            /app/adguardhome-sync/adguardhome-sync run --config "${CONFIGFILE:-/config/adguardhome-sync.yaml}"
else
    exec \
        s6-notifyoncheck -d -n 300 -w 1000 \
            s6-setuidgid abc /app/adguardhome-sync/adguardhome-sync run --config "${CONFIGFILE:-/config/adguardhome-sync.yaml}"
fi
